name: Update Nix packages

on:
  workflow_dispatch:
  schedule:
    - cron: "* * 1-7 */2 6" # First Saturday every second month

jobs:
  update:
    uses: jpaju/gh-commons/.github/workflows/nix-flake-update.yml@main
